create table "public"."actions" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "type" text not null default ''::text,
    "level" text not null default ''::text,
    "state" text,
    "chamber" text not null default ''::text,
    "congress" smallint,
    "bill_type" text,
    "number" integer,
    "introduced_at" date,
    "official_title" text,
    "popular_title" text,
    "short_title" text,
    "sponsor_id" text,
    "sponsor_type" text,
    "status" text,
    "status_at" timestamp with time zone,
    "tags" text[],
    "top_tag" text,
    "summary" jsonb,
    "cache_updated_at" timestamp with time zone,
    "source_url" text,
    "session_id" bigint not null
);


alter table "public"."actions" enable row level security;

create table "public"."bill_amendments" (
    "created_at" timestamp with time zone not null default now(),
    "action_id" text not null,
    "type" text,
    "chamber" text,
    "congress" smallint,
    "number" integer,
    "description" text,
    "introduced_at" date,
    "sponsor_id" text,
    "status" text,
    "status_at" timestamp with time zone,
    "cache_updated_at" timestamp with time zone,
    "id" text not null
);


alter table "public"."bill_amendments" enable row level security;

create table "public"."bill_cosponsors" (
    "rep_id" text not null,
    "action_id" text not null,
    "original_cosponsor" boolean,
    "sponsored_at" timestamp with time zone,
    "withdrawn_at" timestamp with time zone
);


alter table "public"."bill_cosponsors" enable row level security;

create table "public"."db_updates" (
    "script_id" text not null,
    "last_run" timestamp with time zone,
    "status" text
);


alter table "public"."db_updates" enable row level security;

create table "public"."rep_votes" (
    "rep_id" text not null,
    "vote_id" uuid not null default gen_random_uuid(),
    "vote" text not null
);


alter table "public"."rep_votes" enable row level security;

create table "public"."representatives" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "full_name" text not null default ''::text,
    "first_name" text not null default ''::text,
    "last_name" text not null default ''::text,
    "homepage" text
);


alter table "public"."representatives" enable row level security;

create table "public"."sessions" (
    "id" bigint generated by default as identity not null,
    "level" text not null,
    "state" text,
    "chamber" text,
    "congress" smallint,
    "title" text,
    "start_date" date,
    "end_date" date
);


alter table "public"."sessions" enable row level security;

create table "public"."terms" (
    "rep_id" text not null,
    "session_id" integer not null,
    "state" text,
    "district" smallint,
    "party" text
);


alter table "public"."terms" enable row level security;

create table "public"."votes" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "action_id" text not null,
    "result" text,
    "question" text,
    "type" text,
    "chamber" text,
    "congress" smallint,
    "session" bigint,
    "requires" text,
    "number" integer,
    "date" timestamp with time zone,
    "cache_updated_at" timestamp with time zone,
    "alternate_id" text
);


alter table "public"."votes" enable row level security;

CREATE UNIQUE INDEX actions_id_key ON public.actions USING btree (id);

CREATE UNIQUE INDEX actions_pkey ON public.actions USING btree (id);

CREATE UNIQUE INDEX bill_amendments_pkey ON public.bill_amendments USING btree (id);

CREATE UNIQUE INDEX bill_cosponsors_pkey ON public.bill_cosponsors USING btree (rep_id, action_id);

CREATE UNIQUE INDEX db_updates_pkey ON public.db_updates USING btree (script_id);

CREATE UNIQUE INDEX rep_votes_pkey ON public.rep_votes USING btree (rep_id, vote_id);

CREATE INDEX rep_votes_rep_id_idx ON public.rep_votes USING btree (rep_id);

CREATE UNIQUE INDEX representatives_pkey ON public.representatives USING btree (id);

CREATE UNIQUE INDEX sessions_pkey ON public.sessions USING btree (id);

CREATE UNIQUE INDEX terms_pkey ON public.terms USING btree (rep_id, session_id);

CREATE UNIQUE INDEX votes_alternate_id_key ON public.votes USING btree (alternate_id);

CREATE UNIQUE INDEX votes_pkey ON public.votes USING btree (id);

alter table "public"."actions" add constraint "actions_pkey" PRIMARY KEY using index "actions_pkey";

alter table "public"."bill_amendments" add constraint "bill_amendments_pkey" PRIMARY KEY using index "bill_amendments_pkey";

alter table "public"."bill_cosponsors" add constraint "bill_cosponsors_pkey" PRIMARY KEY using index "bill_cosponsors_pkey";

alter table "public"."db_updates" add constraint "db_updates_pkey" PRIMARY KEY using index "db_updates_pkey";

alter table "public"."rep_votes" add constraint "rep_votes_pkey" PRIMARY KEY using index "rep_votes_pkey";

alter table "public"."representatives" add constraint "representatives_pkey" PRIMARY KEY using index "representatives_pkey";

alter table "public"."sessions" add constraint "sessions_pkey" PRIMARY KEY using index "sessions_pkey";

alter table "public"."terms" add constraint "terms_pkey" PRIMARY KEY using index "terms_pkey";

alter table "public"."votes" add constraint "votes_pkey" PRIMARY KEY using index "votes_pkey";

alter table "public"."actions" add constraint "actions_id_key" UNIQUE using index "actions_id_key";

alter table "public"."actions" add constraint "actions_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) not valid;

alter table "public"."actions" validate constraint "actions_session_id_fkey";

alter table "public"."actions" add constraint "actions_sponsor_id_fkey" FOREIGN KEY (sponsor_id) REFERENCES representatives(id) not valid;

alter table "public"."actions" validate constraint "actions_sponsor_id_fkey";

alter table "public"."bill_amendments" add constraint "bill_amendments_action_id_fkey" FOREIGN KEY (action_id) REFERENCES actions(id) ON DELETE CASCADE not valid;

alter table "public"."bill_amendments" validate constraint "bill_amendments_action_id_fkey";

alter table "public"."bill_amendments" add constraint "bill_amendments_sponsor_id_fkey" FOREIGN KEY (sponsor_id) REFERENCES representatives(id) not valid;

alter table "public"."bill_amendments" validate constraint "bill_amendments_sponsor_id_fkey";

alter table "public"."bill_cosponsors" add constraint "bill_cosponsors_action_id_fkey" FOREIGN KEY (action_id) REFERENCES actions(id) ON DELETE CASCADE not valid;

alter table "public"."bill_cosponsors" validate constraint "bill_cosponsors_action_id_fkey";

alter table "public"."bill_cosponsors" add constraint "bill_cosponsors_rep_id_fkey" FOREIGN KEY (rep_id) REFERENCES representatives(id) not valid;

alter table "public"."bill_cosponsors" validate constraint "bill_cosponsors_rep_id_fkey";

alter table "public"."rep_votes" add constraint "rep_votes_rep_id_fkey" FOREIGN KEY (rep_id) REFERENCES representatives(id) not valid;

alter table "public"."rep_votes" validate constraint "rep_votes_rep_id_fkey";

alter table "public"."rep_votes" add constraint "rep_votes_vote_id_fkey" FOREIGN KEY (vote_id) REFERENCES votes(id) ON DELETE CASCADE not valid;

alter table "public"."rep_votes" validate constraint "rep_votes_vote_id_fkey";

alter table "public"."terms" add constraint "terms_rep_id_fkey" FOREIGN KEY (rep_id) REFERENCES representatives(id) not valid;

alter table "public"."terms" validate constraint "terms_rep_id_fkey";

alter table "public"."terms" add constraint "terms_session_id_fkey" FOREIGN KEY (session_id) REFERENCES sessions(id) not valid;

alter table "public"."terms" validate constraint "terms_session_id_fkey";

alter table "public"."votes" add constraint "votes_action_id_fkey" FOREIGN KEY (action_id) REFERENCES actions(id) ON DELETE CASCADE not valid;

alter table "public"."votes" validate constraint "votes_action_id_fkey";

alter table "public"."votes" add constraint "votes_alternate_id_key" UNIQUE using index "votes_alternate_id_key";

alter table "public"."votes" add constraint "votes_session_fkey" FOREIGN KEY (session) REFERENCES sessions(id) not valid;

alter table "public"."votes" validate constraint "votes_session_fkey";

grant delete on table "public"."actions" to "anon";

grant insert on table "public"."actions" to "anon";

grant references on table "public"."actions" to "anon";

grant select on table "public"."actions" to "anon";

grant trigger on table "public"."actions" to "anon";

grant truncate on table "public"."actions" to "anon";

grant update on table "public"."actions" to "anon";

grant delete on table "public"."actions" to "authenticated";

grant insert on table "public"."actions" to "authenticated";

grant references on table "public"."actions" to "authenticated";

grant select on table "public"."actions" to "authenticated";

grant trigger on table "public"."actions" to "authenticated";

grant truncate on table "public"."actions" to "authenticated";

grant update on table "public"."actions" to "authenticated";

grant delete on table "public"."actions" to "service_role";

grant insert on table "public"."actions" to "service_role";

grant references on table "public"."actions" to "service_role";

grant select on table "public"."actions" to "service_role";

grant trigger on table "public"."actions" to "service_role";

grant truncate on table "public"."actions" to "service_role";

grant update on table "public"."actions" to "service_role";

grant delete on table "public"."bill_amendments" to "anon";

grant insert on table "public"."bill_amendments" to "anon";

grant references on table "public"."bill_amendments" to "anon";

grant select on table "public"."bill_amendments" to "anon";

grant trigger on table "public"."bill_amendments" to "anon";

grant truncate on table "public"."bill_amendments" to "anon";

grant update on table "public"."bill_amendments" to "anon";

grant delete on table "public"."bill_amendments" to "authenticated";

grant insert on table "public"."bill_amendments" to "authenticated";

grant references on table "public"."bill_amendments" to "authenticated";

grant select on table "public"."bill_amendments" to "authenticated";

grant trigger on table "public"."bill_amendments" to "authenticated";

grant truncate on table "public"."bill_amendments" to "authenticated";

grant update on table "public"."bill_amendments" to "authenticated";

grant delete on table "public"."bill_amendments" to "service_role";

grant insert on table "public"."bill_amendments" to "service_role";

grant references on table "public"."bill_amendments" to "service_role";

grant select on table "public"."bill_amendments" to "service_role";

grant trigger on table "public"."bill_amendments" to "service_role";

grant truncate on table "public"."bill_amendments" to "service_role";

grant update on table "public"."bill_amendments" to "service_role";

grant delete on table "public"."bill_cosponsors" to "anon";

grant insert on table "public"."bill_cosponsors" to "anon";

grant references on table "public"."bill_cosponsors" to "anon";

grant select on table "public"."bill_cosponsors" to "anon";

grant trigger on table "public"."bill_cosponsors" to "anon";

grant truncate on table "public"."bill_cosponsors" to "anon";

grant update on table "public"."bill_cosponsors" to "anon";

grant delete on table "public"."bill_cosponsors" to "authenticated";

grant insert on table "public"."bill_cosponsors" to "authenticated";

grant references on table "public"."bill_cosponsors" to "authenticated";

grant select on table "public"."bill_cosponsors" to "authenticated";

grant trigger on table "public"."bill_cosponsors" to "authenticated";

grant truncate on table "public"."bill_cosponsors" to "authenticated";

grant update on table "public"."bill_cosponsors" to "authenticated";

grant delete on table "public"."bill_cosponsors" to "service_role";

grant insert on table "public"."bill_cosponsors" to "service_role";

grant references on table "public"."bill_cosponsors" to "service_role";

grant select on table "public"."bill_cosponsors" to "service_role";

grant trigger on table "public"."bill_cosponsors" to "service_role";

grant truncate on table "public"."bill_cosponsors" to "service_role";

grant update on table "public"."bill_cosponsors" to "service_role";

grant delete on table "public"."db_updates" to "anon";

grant insert on table "public"."db_updates" to "anon";

grant references on table "public"."db_updates" to "anon";

grant select on table "public"."db_updates" to "anon";

grant trigger on table "public"."db_updates" to "anon";

grant truncate on table "public"."db_updates" to "anon";

grant update on table "public"."db_updates" to "anon";

grant delete on table "public"."db_updates" to "authenticated";

grant insert on table "public"."db_updates" to "authenticated";

grant references on table "public"."db_updates" to "authenticated";

grant select on table "public"."db_updates" to "authenticated";

grant trigger on table "public"."db_updates" to "authenticated";

grant truncate on table "public"."db_updates" to "authenticated";

grant update on table "public"."db_updates" to "authenticated";

grant delete on table "public"."db_updates" to "service_role";

grant insert on table "public"."db_updates" to "service_role";

grant references on table "public"."db_updates" to "service_role";

grant select on table "public"."db_updates" to "service_role";

grant trigger on table "public"."db_updates" to "service_role";

grant truncate on table "public"."db_updates" to "service_role";

grant update on table "public"."db_updates" to "service_role";

grant delete on table "public"."rep_votes" to "anon";

grant insert on table "public"."rep_votes" to "anon";

grant references on table "public"."rep_votes" to "anon";

grant select on table "public"."rep_votes" to "anon";

grant trigger on table "public"."rep_votes" to "anon";

grant truncate on table "public"."rep_votes" to "anon";

grant update on table "public"."rep_votes" to "anon";

grant delete on table "public"."rep_votes" to "authenticated";

grant insert on table "public"."rep_votes" to "authenticated";

grant references on table "public"."rep_votes" to "authenticated";

grant select on table "public"."rep_votes" to "authenticated";

grant trigger on table "public"."rep_votes" to "authenticated";

grant truncate on table "public"."rep_votes" to "authenticated";

grant update on table "public"."rep_votes" to "authenticated";

grant delete on table "public"."rep_votes" to "service_role";

grant insert on table "public"."rep_votes" to "service_role";

grant references on table "public"."rep_votes" to "service_role";

grant select on table "public"."rep_votes" to "service_role";

grant trigger on table "public"."rep_votes" to "service_role";

grant truncate on table "public"."rep_votes" to "service_role";

grant update on table "public"."rep_votes" to "service_role";

grant delete on table "public"."representatives" to "anon";

grant insert on table "public"."representatives" to "anon";

grant references on table "public"."representatives" to "anon";

grant select on table "public"."representatives" to "anon";

grant trigger on table "public"."representatives" to "anon";

grant truncate on table "public"."representatives" to "anon";

grant update on table "public"."representatives" to "anon";

grant delete on table "public"."representatives" to "authenticated";

grant insert on table "public"."representatives" to "authenticated";

grant references on table "public"."representatives" to "authenticated";

grant select on table "public"."representatives" to "authenticated";

grant trigger on table "public"."representatives" to "authenticated";

grant truncate on table "public"."representatives" to "authenticated";

grant update on table "public"."representatives" to "authenticated";

grant delete on table "public"."representatives" to "service_role";

grant insert on table "public"."representatives" to "service_role";

grant references on table "public"."representatives" to "service_role";

grant select on table "public"."representatives" to "service_role";

grant trigger on table "public"."representatives" to "service_role";

grant truncate on table "public"."representatives" to "service_role";

grant update on table "public"."representatives" to "service_role";

grant delete on table "public"."sessions" to "anon";

grant insert on table "public"."sessions" to "anon";

grant references on table "public"."sessions" to "anon";

grant select on table "public"."sessions" to "anon";

grant trigger on table "public"."sessions" to "anon";

grant truncate on table "public"."sessions" to "anon";

grant update on table "public"."sessions" to "anon";

grant delete on table "public"."sessions" to "authenticated";

grant insert on table "public"."sessions" to "authenticated";

grant references on table "public"."sessions" to "authenticated";

grant select on table "public"."sessions" to "authenticated";

grant trigger on table "public"."sessions" to "authenticated";

grant truncate on table "public"."sessions" to "authenticated";

grant update on table "public"."sessions" to "authenticated";

grant delete on table "public"."sessions" to "service_role";

grant insert on table "public"."sessions" to "service_role";

grant references on table "public"."sessions" to "service_role";

grant select on table "public"."sessions" to "service_role";

grant trigger on table "public"."sessions" to "service_role";

grant truncate on table "public"."sessions" to "service_role";

grant update on table "public"."sessions" to "service_role";

grant delete on table "public"."terms" to "anon";

grant insert on table "public"."terms" to "anon";

grant references on table "public"."terms" to "anon";

grant select on table "public"."terms" to "anon";

grant trigger on table "public"."terms" to "anon";

grant truncate on table "public"."terms" to "anon";

grant update on table "public"."terms" to "anon";

grant delete on table "public"."terms" to "authenticated";

grant insert on table "public"."terms" to "authenticated";

grant references on table "public"."terms" to "authenticated";

grant select on table "public"."terms" to "authenticated";

grant trigger on table "public"."terms" to "authenticated";

grant truncate on table "public"."terms" to "authenticated";

grant update on table "public"."terms" to "authenticated";

grant delete on table "public"."terms" to "service_role";

grant insert on table "public"."terms" to "service_role";

grant references on table "public"."terms" to "service_role";

grant select on table "public"."terms" to "service_role";

grant trigger on table "public"."terms" to "service_role";

grant truncate on table "public"."terms" to "service_role";

grant update on table "public"."terms" to "service_role";

grant delete on table "public"."votes" to "anon";

grant insert on table "public"."votes" to "anon";

grant references on table "public"."votes" to "anon";

grant select on table "public"."votes" to "anon";

grant trigger on table "public"."votes" to "anon";

grant truncate on table "public"."votes" to "anon";

grant update on table "public"."votes" to "anon";

grant delete on table "public"."votes" to "authenticated";

grant insert on table "public"."votes" to "authenticated";

grant references on table "public"."votes" to "authenticated";

grant select on table "public"."votes" to "authenticated";

grant trigger on table "public"."votes" to "authenticated";

grant truncate on table "public"."votes" to "authenticated";

grant update on table "public"."votes" to "authenticated";

grant delete on table "public"."votes" to "service_role";

grant insert on table "public"."votes" to "service_role";

grant references on table "public"."votes" to "service_role";

grant select on table "public"."votes" to "service_role";

grant trigger on table "public"."votes" to "service_role";

grant truncate on table "public"."votes" to "service_role";

grant update on table "public"."votes" to "service_role";

create policy "Enable read access for all users"
on "public"."actions"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."bill_amendments"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."bill_cosponsors"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."rep_votes"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."representatives"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."sessions"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."terms"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."votes"
as permissive
for select
to public
using (true);



